version: "3.7"
services:
  reltime_node:
    image: hyperledger/besu:latest
    container_name: "genesis-generator"
    volumes:
      - .:/usr/app/
    command: operator generate-blockchain-config --config-file=/usr/app/ibftConfigFile.json --to=/usr/app/networkFiles --private-key-file-name=key
volumes:
  .:
